name: crypto-exchange-environment

services:
  crypto-exchange-api:
    image: ${DOCKER_REGISTRY-}cryptoexchangeapi
    build:
      context: .
      dockerfile: CryptoExchangeTask.Presentation.Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - crypto-exchange-network

networks:
  crypto-exchange-network:
    name: crypto-exchange-network
    driver: bridge